version: "3"
services:
  ui-service-cont:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./:/myapp2
      - /myapp/node_modules
    environment:
      - PORT=3001
    depends_on:
      - mongo
    # networks:
    #   - uinetwork
  mongo:
    image: mongo
    # environment:
    #   - MONGO_INIT_ROOT_USERNAME=yash
    #   - MONGO_INIT_ROOT_USERNAME=mypassword  
    volumes:
      - mongo-db:/data/db2
volumes:
  mongo-db:
# networks:
#   uinetwork:
#     driver: bridge
#     # external:true