version: "3"
services:
  ui:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./:/myapp2
      - /myapp2/node_modules
    environment:
      - PORT=3001
    depends_on:
      - mongo
    # networks:
    #   - uinetwork
  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db2
volumes:
  mongo-db:

networks:
  default:
    external:
      name: bridge-network